/* ============================================================
   Reiseführer China · Reisedaten
   Route: Hongkong → Shenzhen → Guilin → Yangshuo → Xi'an
          → Peking → Shanghai  (5× Schnellzug, 1× Inlandsflug)
   ============================================================ */

/* Zentrale Reise-Konfiguration – hier das Startdatum ändern,
   alle Tagesangaben rechnen sich daraus automatisch. */
const TRIP = {
  start: "2026-09-09",   // Tag 1
  endLabel: "30. September 2026",
  totalDays: 22,
  totalNights: 21,
};

/* Kinderwagen-Hinweise */
const STROLLER = {
  yes:     { label: "Kinderwagen ok", emoji: "🛒", cls: "stroller-yes" },
  careful: { label: "Teils Stufen",   emoji: "⚠",  cls: "stroller-careful" },
  no:      { label: "Lieber Trage",   emoji: "🤱", cls: "stroller-no" },
};

/* Generisches SVG für Restaurants */
const FOOD_SVG =
  "data:image/svg+xml;utf8," +
  encodeURIComponent(`
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 200">
    <defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0" stop-color="#fbeee4"/><stop offset="1" stop-color="#e8c9a8"/>
    </linearGradient></defs>
    <rect width="320" height="200" fill="url(#g)"/>
    <g transform="translate(160 96)" fill="none" stroke="#a8322a" stroke-width="3" stroke-linecap="round">
      <circle r="40" fill="#fff8f2"/><circle r="27" stroke-width="2"/>
      <path d="M -58 -14 L -30 8 M -52 -20 L -24 2"/>
      <path d="M 26 -18 L 54 -18 M 26 -10 L 54 -10"/>
    </g>
    <text x="160" y="172" text-anchor="middle" font-family="Cormorant Garamond, serif" font-style="italic" font-size="19" fill="#a8322a">China · Essen</text>
  </svg>`);

/* ============================================================
   ETAPPEN – die Verbindungen zwischen den Städten
   ============================================================ */
const LEGS = [
  { from: "Stuttgart / Frankfurt", to: "Hongkong", mode: "plane",
    icon: "✈️", duration: "Langstrecke", note: "Ankunft Hongkong – Anreise ins Hotel per Airport Express (24 Min. bis Kowloon)." },
  { from: "HK West Kowloon", to: "Shenzhen Futian", mode: "train",
    icon: "🚄", duration: "14–19 Min.", note: "Kürzeste Etappe der Reise. Achtung: echte Grenzkontrolle – Pässe bereithalten, Zeitpuffer einplanen." },
  { from: "Shenzhen North", to: "Guilin North", mode: "train",
    icon: "🚄", duration: "ca. 2 h 40", note: "Schnellste Züge ~2 h 39. Beim Buchen auf die Fahrzeit achten – es gibt auch Züge mit über 5 Stunden." },
  { from: "Guilin", to: "Yangshuo", mode: "bus",
    icon: "🚌", duration: "70–90 Min.", note: "Bus ab Guilin Railway Station fährt direkt ins Zentrum von Yangshuo. Der Bahnhof „Yangshuo“ liegt 34 km außerhalb – mit Kinderwagen ist der Bus klar die bessere Wahl." },
  { from: "Guilin (KWL)", to: "Xi'an (XIY)", mode: "plane",
    icon: "✈️", duration: "ca. 2 h 05", note: "Der EINZIGE Inlandsflug. Ersetzt eine 8–11-stündige Zugfahrt. Ca. 5 Verbindungen täglich." },
  { from: "Xi'an North", to: "Peking West", mode: "train",
    icon: "🚄", duration: "ab 4 h 11", note: "1.216 km mit 300 km/h. Die schnellsten Züge halten nur einmal (Zhengzhou East)." },
  { from: "Peking South", to: "Shanghai Hongqiao", mode: "train",
    icon: "🚄", duration: "ab 4 h 18", note: "Die berühmteste Schnellzugstrecke Chinas, 1.318 km. WICHTIG: Ticket früh buchen – kurz vor dem Mittherbstfest." },
  { from: "Shanghai (PVG)", to: "Heimreise", mode: "plane",
    icon: "✈️", duration: "Langstrecke", note: "Abflug am 30.09. – bewusst einen Tag vor Beginn der Golden Week (ab 01.10.)." },
];

/* ============================================================
   STÄDTE
   Felder pro Location: name, cn, mapsName, desc, image,
   lat, lng, stroller, badges[], ticketUrl, inRoute
   ============================================================ */
const CITIES = [
  /* ========================= HONGKONG ========================= */
  {
    id: "hongkong",
    name: "Hongkong",
    cn: "香港",
    country: "Sonderverwaltungszone",
    dateLabel: "09.–12. September",
    dayLabel: "Tag 1–4",
    nights: 3,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Night_view_of_Hong_Kong_from_Tsim_Sha_Tsui.jpg/1280px-Night_view_of_Hong_Kong_from_Tsim_Sha_Tsui.jpg",
    summary: "Wolkenkratzer, Fähren und Bergblick: der perfekte, entspannte Einstieg. Englisch wird überall gesprochen, Google Maps funktioniert hier noch.",
    highlights: ["Victoria Peak", "Star Ferry", "Großer Buddha"],
    hotel: {
      name: "Eaton HK",
      address: "380 Nathan Road, Jordan, Kowloon",
      mapsName: "Eaton HK, 380 Nathan Road, Hong Kong",
      lat: 22.30806, lng: 114.17183,
      price: "95–170 € / Nacht",
      why: "Babybett kostenlos. Auf Anfrage gibt es zusätzlich Laufstall, Kinderwagen, Baby-Badewanne, Flaschensterilisator und Hochstuhl. Rooftop-Pool im 21. Stock.",
      transfer: "Jordan MTR 5 Min. zu Fuß · West Kowloon Schnellzug-Bahnhof 22 Min. zu Fuß oder ~HK$35 Taxi",
    },
    intro: "Startet langsam – nach dem Langstreckenflug braucht der Kleine Zeit zum Ankommen. Hongkong ist ideal dafür: kompakt, gut beschildert, viele Parks und überall Klimaanlage.",
    zones: [
      {
        id: "hk-island",
        tag: "Tag-Idee · Insel",
        title: "Hong Kong Island – Peak & Hafen",
        summary: "Mit der historischen Peak Tram auf den Berg, dann Skyline von oben, Tempel-Duft in Sheung Wan und ein grüner Park mitten zwischen Wolkenkratzern.",
        walkFromHotel: "Mit Star Ferry / MTR ~20 Min., vor Ort zu Fuß",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/High_West_and_Victoria_Peak_from_Victoria_Gap_%28crop1%29.jpg/1280px-High_West_and_Victoria_Peak_from_Victoria_Gap_%28crop1%29.jpg",
        transportNote: "Vom Hotel mit der MTR (Tsuen Wan Line) unter dem Hafen hindurch nach Central – oder schöner: zu Fuß zur Star Ferry und mit dem Schiff hinüber. Die Peak Tram ist seit 2022 modernisiert und nimmt Kinderwagen mit; oben ist alles eben.",
        route: { fromHotel: false, mode: "transit" },
        sights: [
          { name: "Victoria Peak & Peak Tram", cn: "太平山頂", mapsName: "Victoria Peak, Hong Kong",
            desc: "Der klassische Blick über die Skyline und den Hafen. Die Standseilbahn zieht euch in 5 Minuten fast senkrecht den Berg hinauf – ein Erlebnis für sich. Oben gibt es einen ebenen Rundweg (Lugard Road).",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/High_West_and_Victoria_Peak_from_Victoria_Gap_%28crop1%29.jpg/1280px-High_West_and_Victoria_Peak_from_Victoria_Gap_%28crop1%29.jpg",
            lat: 22.2759, lng: 114.1455, stroller: "careful",
            badges: ["Tickets vorab online", "Oben eben – Lugard Road", "Bei Nebel wenig Sicht"],
            ticketUrl: "https://www.thepeak.com.hk/en" },
          { name: "Star Ferry", cn: "天星小輪", mapsName: "Star Ferry Pier Tsim Sha Tsui, Hong Kong",
            desc: "Seit 1888 pendeln die grün-weißen Fähren über den Hafen – für ein paar Hongkong-Dollar die günstigste Hafenrundfahrt der Welt. Der Kinderwagen kann einfach mit an Bord geschoben werden.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/2024-12-27_A_Star_Ferry_crosses_Victoria_Harbour_1.jpg/1280px-2024-12-27_A_Star_Ferry_crosses_Victoria_Harbour_1.jpg",
            lat: 22.2938, lng: 114.1686, stroller: "yes",
            badges: ["Sehr günstig", "Unteres Deck ohne Stufen"] },
          { name: "Man Mo Tempel", cn: "文武廟", mapsName: "Man Mo Temple, Hollywood Road, Hong Kong",
            desc: "Kleiner Taoisten-Tempel von 1847 mit riesigen Weihrauchspiralen unter der Decke. Sehr atmosphärisch – aber der dichte Rauch ist für Babys nicht ideal, also nur kurz hinein.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Man_Mo_Temple%2C_1847-62%2C_Sheung_Wan%2C_Hong_Kong_%2817%29_%2832748033042%29.jpg/1280px-Man_Mo_Temple%2C_1847-62%2C_Sheung_Wan%2C_Hong_Kong_%2817%29_%2832748033042%29.jpg",
            lat: 22.2839, lng: 114.1503, stroller: "careful",
            badges: ["Eintritt frei", "Viel Weihrauch – kurz bleiben", "Steile Straßen ringsum"] },
          { name: "Hong Kong Park", cn: "香港公園", mapsName: "Hong Kong Park, Central, Hong Kong",
            desc: "Grüne Oase zwischen den Hochhäusern mit Wasserfall, Teichen und einer begehbaren Vogelvoliere. Breite, ebene Wege und viel Schatten – perfekt für die Mittagspause mit Baby.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Hong_Kong_Park_Overview_2009.jpg/1280px-Hong_Kong_Park_Overview_2009.jpg",
            lat: 22.2775, lng: 114.1620, stroller: "yes",
            badges: ["Eintritt frei", "Vogelvoliere", "Viel Schatten"] },
        ],
        restaurants: [
          { name: "Tim Ho Wan (Dim Sum)", mapsName: "Tim Ho Wan, Hong Kong",
            desc: "Legendäre Dim-Sum-Kette, bekannt als eines der günstigsten Sterne-Restaurants der Welt. Gedämpfte Teigtaschen sind auch für kleine Kinder gut geeignet.",
            lat: 22.2830, lng: 114.1560, price: "8–15 € / Person",
            badges: ["Dim Sum", "Gedämpft statt frittiert"] },
          { name: "Lin Heung Tea House", mapsName: "Lin Heung Tea House, Hong Kong",
            desc: "Traditionelles Teehaus alter Schule mit rollenden Dim-Sum-Wagen. Laut, voll und ein echtes Stück altes Hongkong – am besten vormittags.",
            lat: 22.2845, lng: 114.1540, price: "8–14 € / Person",
            badges: ["Traditionell", "Vormittags gehen"] },
          { name: "Grassroots Pantry / vegetarische Küche", mapsName: "vegetarian restaurant Sheung Wan Hong Kong",
            desc: "Hongkong hat eine große vegetarisch-vegane Szene rund um Sheung Wan und Central: Bowls, Salate, pflanzliche Küche mit vielen glutenfrei gekennzeichneten Gerichten.",
            lat: 22.2860, lng: 114.1490, price: "12–22 € / Gericht",
            badges: ["Gesund", "Vegetarisch", "Glutenfrei möglich"] },
        ],
      },
      {
        id: "hk-kowloon",
        tag: "Tag-Idee · Kowloon",
        title: "Kowloon – Promenade, Parks & Märkte",
        summary: "Die berühmteste Aussicht auf die Skyline liegt direkt vor eurer Haustür: die Uferpromenade in Tsim Sha Tsui, dazu Parks und der abendliche Temple Street Markt.",
        walkFromHotel: "Alles zu Fuß bzw. 1–2 MTR-Stationen",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Harbour_night_%2850561805203%29.jpg/1280px-Harbour_night_%2850561805203%29.jpg",
        transportNote: "Das ist euer Hotelviertel – fast alles ist fußläufig oder eine MTR-Station entfernt. Die Promenade ist komplett eben und breit, ideal zum Schieben. Um 20 Uhr läuft täglich die Lichtshow „Symphony of Lights“ über dem Hafen.",
        route: { fromHotel: true, mode: "walking" },
        sights: [
          { name: "Tsim Sha Tsui Promenade & Avenue of Stars", cn: "尖沙咀海濱", mapsName: "Avenue of Stars, Tsim Sha Tsui, Hong Kong",
            desc: "Die schönste Skyline-Aussicht der Stadt, komplett eben und barrierefrei. Abends um 20 Uhr färbt die Lichtshow „Symphony of Lights“ die Hochhäuser.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Harbour_night_%2850561805203%29.jpg/1280px-Harbour_night_%2850561805203%29.jpg",
            lat: 22.2934, lng: 114.1722, stroller: "yes",
            badges: ["Kostenlos", "Komplett eben", "20 Uhr Lichtshow"] },
          { name: "Kowloon Park", cn: "九龍公園", mapsName: "Kowloon Park, Tsim Sha Tsui, Hong Kong",
            desc: "Großer Stadtpark mit Flamingo-Teich, Spielplätzen und schattigen Wegen – nur wenige Minuten vom Hotel. Die beste Rückzugsinsel, wenn es dem Baby zu voll wird.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Hong_Kong_Park_Overview_2009.jpg/1280px-Hong_Kong_Park_Overview_2009.jpg",
            lat: 22.3003, lng: 114.1706, stroller: "yes",
            badges: ["Eintritt frei", "Spielplätze", "Flamingos"] },
          { name: "Temple Street Nachtmarkt", cn: "廟街", mapsName: "Temple Street Night Market, Hong Kong",
            desc: "Klassischer Straßenmarkt mit Garküchen, Souvenirs und Wahrsagern, der ab dem frühen Abend erwacht. Eng und voll – mit Kinderwagen eher am Rand bleiben.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/GateOfTempleInHongKong.jpg/1280px-GateOfTempleInHongKong.jpg",
            lat: 22.3068, lng: 114.1700, stroller: "careful",
            badges: ["Ab ca. 18 Uhr", "Eng – Trage besser", "Nur 10 Min. vom Hotel"] },
          { name: "Wong Tai Sin Tempel", cn: "黃大仙祠", mapsName: "Wong Tai Sin Temple, Hong Kong",
            desc: "Farbenprächtigster Tempel der Stadt, direkt an der gleichnamigen MTR-Station. Weitläufige Anlage mit Gärten; Rampen sind vorhanden, einzelne Treppen aber auch.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/HK_WongTaiSinTemple.JPG/1280px-HK_WongTaiSinTemple.JPG",
            lat: 22.3423, lng: 114.1935, stroller: "careful",
            badges: ["Direkt an der MTR", "Einzelne Treppen"] },
        ],
        restaurants: [
          { name: "Australia Dairy Company", mapsName: "Australia Dairy Company, Jordan, Hong Kong",
            desc: "Kult-Frühstückslokal um die Ecke vom Hotel: Rührei auf Toast, Milchpudding, rasanter Service. Günstig und schnell – ideal vor dem Losziehen.",
            lat: 22.3050, lng: 114.1710, price: "5–10 € / Person",
            badges: ["Frühstück", "Sehr schnell", "Nah am Hotel"] },
          { name: "Din Tai Fung", mapsName: "Din Tai Fung Tsim Sha Tsui, Hong Kong",
            desc: "Berühmt für Xiao Long Bao (Suppen-Teigtaschen). Sauber, familienfreundlich, Hochstühle vorhanden – eine verlässliche Wahl mit Kind.",
            lat: 22.2980, lng: 114.1720, price: "15–25 € / Person",
            badges: ["Familienfreundlich", "Hochstühle"] },
          { name: "Kowloon Park Food Court & gesunde Cafés", mapsName: "healthy cafe Tsim Sha Tsui Hong Kong",
            desc: "Rund um TST gibt es zahlreiche Bowl- und Saft-Cafés mit Salaten, Smoothies und glutenfrei markierten Optionen – eine leichte Alternative zur schweren Küche.",
            lat: 22.2990, lng: 114.1715, price: "10–18 € / Gericht",
            badges: ["Gesund", "Bowls", "Glutenfrei möglich"] },
        ],
      },
      {
        id: "hk-lantau",
        tag: "Tag-Idee · Ausflug",
        title: "Lantau – Großer Buddha & Fischerdorf",
        summary: "Mit der Seilbahn über Berge und Meer zum 34 Meter hohen Tian-Tan-Buddha, dazu das Stelzendorf Tai O. Ein voller, aber unvergesslicher Tag.",
        walkFromHotel: "MTR bis Tung Chung (~40 Min.), dann Seilbahn",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Tian_Tan_Buddha_2023081302.jpg/1280px-Tian_Tan_Buddha_2023081302.jpg",
        transportNote: "MTR Tung Chung Line bis Endstation Tung Chung (~40 Min. ab Hotel), dann mit „Ngong Ping 360“ in 25 Min. über die Berge. Seilbahn-Tickets unbedingt vorab online buchen. Alternative bei Wind/Wartezeit: Bus 23 hinauf. Wichtig mit Baby: früh starten, es wird ein langer Tag.",
        route: { fromHotel: false, mode: "transit" },
        sights: [
          { name: "Ngong Ping 360 Seilbahn", cn: "昂坪360", mapsName: "Ngong Ping 360 Tung Chung Terminal, Hong Kong",
            desc: "25 Minuten schwebend über Meer und grüne Berge – landschaftlich eine der schönsten Seilbahnen Asiens. Kinderwagen müssen zusammengeklappt werden.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Ngong_Ping_360_Cable_Car_and_HKG_2021-09.jpg/1280px-Ngong_Ping_360_Cable_Car_and_HKG_2021-09.jpg",
            lat: 22.2891, lng: 113.9411, stroller: "careful",
            badges: ["Tickets vorab!", "Kinderwagen falten", "Bei Sturm geschlossen"],
            ticketUrl: "https://www.np360.com.hk/en/" },
          { name: "Tian Tan Buddha (Großer Buddha)", cn: "天壇大佛", mapsName: "Tian Tan Buddha, Lantau Island, Hong Kong",
            desc: "34 Meter hohe Bronzestatue auf einem Hügel, sichtbar von weitem. Zum Sockel führen 268 Stufen – mit Baby also nur mit Trage, oder man genießt ihn von unten.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Tian_Tan_Buddha_2023081302.jpg/1280px-Tian_Tan_Buddha_2023081302.jpg",
            lat: 22.2540, lng: 113.9050, stroller: "no",
            badges: ["268 Stufen → Trage", "Von unten auch schön"] },
          { name: "Po Lin Kloster", cn: "寶蓮禪寺", mapsName: "Po Lin Monastery, Lantau Island, Hong Kong",
            desc: "Farbenfrohes buddhistisches Kloster direkt gegenüber dem Buddha, mit bekanntem vegetarischem Restaurant. Das Gelände selbst ist weitgehend eben.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Po_Lin_Monastery_2.jpg/1280px-Po_Lin_Monastery_2.jpg",
            lat: 22.2544, lng: 113.9060, stroller: "careful",
            badges: ["Vegetarisches Restaurant", "Gelände eben"] },
          { name: "Tai O Fischerdorf", cn: "大澳", mapsName: "Tai O Fishing Village, Lantau, Hong Kong",
            desc: "Altes Stelzendorf auf Pfählen über dem Wasser – ein völlig anderes Hongkong. Kleine Bootstouren, auf denen man mit Glück rosa Delfine sieht.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/1_tai_o_hong_kong_2013.jpg/1280px-1_tai_o_hong_kong_2013.jpg",
            lat: 22.2551, lng: 113.8628, stroller: "careful",
            badges: ["Bus ab Ngong Ping", "Enge Gassen", "Bootstouren"] },
        ],
        restaurants: [
          { name: "Po Lin Vegetarisches Restaurant", mapsName: "Po Lin Monastery Vegetarian Restaurant, Hong Kong",
            desc: "Klösterliche vegetarische Küche direkt neben dem Buddha – leicht, frisch und ohne Fleisch. Praktisch, weil man vor Ort ohnehin eine Pause braucht.",
            lat: 22.2544, lng: 113.9062, price: "10–18 € / Person",
            badges: ["Vegetarisch", "Gesund", "Direkt vor Ort"] },
          { name: "Tai O Garküchen", mapsName: "Tai O Village food stalls, Hong Kong",
            desc: "Im Dorf gibt es kleine Stände mit gegrilltem Fisch, Reisrollen und frischen Früchten. Reisbasierte Gerichte sind meist von Natur aus glutenfrei.",
            lat: 22.2553, lng: 113.8630, price: "3–9 € / Portion",
            badges: ["Street Food", "Reisbasiert – oft glutenfrei"] },
          { name: "Citygate Outlets Foodcourt (Tung Chung)", mapsName: "Citygate Outlets, Tung Chung, Hong Kong",
            desc: "Klimatisierter Foodcourt direkt an der MTR-Station – der pragmatische Stopp vor oder nach der Seilbahn, mit Wickelraum und großer Auswahl.",
            lat: 22.2890, lng: 113.9410, price: "8–16 € / Gericht",
            badges: ["Klimatisiert", "Wickelraum", "Große Auswahl"] },
        ],
      },
    ],
  },

  /* ========================= SHENZHEN ========================= */
  {
    id: "shenzhen",
    name: "Shenzhen",
    cn: "深圳",
    country: "Provinz Guangdong",
    dateLabel: "12.–13. September",
    dayLabel: "Tag 4–5",
    nights: 1,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Commercial_area_of_futian_to_east2020.jpg/1280px-Commercial_area_of_futian_to_east2020.jpg",
    summary: "Vom Fischerdorf zur Millionen-Metropole in 40 Jahren. Ein kurzer Zwischenstopp, der das moderne China zeigt – und die perfekte Bahnhofs-Etappe.",
    highlights: ["Ping An Tower", "Lianhuashan Park", "OCT-LOFT"],
    hotel: {
      name: "Futian Shangri-La, Shenzhen",
      address: "4088 Yitian Road, Futian District",
      mapsName: "Futian Shangri-La Shenzhen, Yitian Road",
      lat: 22.53892, lng: 114.05239,
      price: "130–230 € / Nacht",
      why: "Babybett kostenlos für Kinder bis 2 Jahre, Badewanne in allen Zimmern und ein beheizter Innenpool. Nur 630 m zum Schnellzug-Bahnhof Futian.",
      transfer: "Bahnhof Futian 630 m (5 Min. zu Fuß) · Metro Shopping Park 340 m (Linien 1, 2, 3, 7)",
    },
    intro: "Nur eine Nacht – bewusst kurz gehalten. Shenzhen ist beeindruckend modern, aber die Highlights der Reise liegen woanders. Nutzt den Tag entspannt: Park, Skyline, Kunstviertel.",
    zones: [
      {
        id: "sz-futian",
        tag: "Tag-Idee · Modernes China",
        title: "Futian, Parks & OCT-Kunstviertel",
        summary: "Grüner Stadtpark mit Skyline-Blick, der 599 m hohe Ping An Tower und das entspannte Kreativviertel OCT-LOFT in alten Fabrikhallen.",
        walkFromHotel: "Metro; Lianhuashan Park 2 Stationen",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Lianhuashan_Garden.jpg/1280px-Lianhuashan_Garden.jpg",
        transportNote: "Shenzhens Metro ist neu, sauber, klimatisiert und fast überall mit Aufzügen ausgestattet – mit Kinderwagen sehr angenehm. Wichtig: Ab hier funktioniert Google Maps nicht mehr zuverlässig. Nutzt die Apple-Karten-Buttons oder ladet euch Amap (高德地图) herunter.",
        route: { fromHotel: true, mode: "transit" },
        sights: [
          { name: "Lianhuashan Park", cn: "莲花山公园", mapsName: "Lianhuashan Park, Futian, Shenzhen",
            desc: "Beliebter Stadtpark mit sanftem Hügel, von dem man den besten kostenlosen Blick auf die Skyline hat. Breite, asphaltierte Wege führen bis fast nach oben – gut mit Kinderwagen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Lianhuashan_Garden.jpg/1280px-Lianhuashan_Garden.jpg",
            lat: 22.5570, lng: 114.0570, stroller: "yes",
            badges: ["Eintritt frei", "Bester Skyline-Blick", "Drachen steigen lassen"] },
          { name: "Ping An Finance Center", cn: "平安金融中心", mapsName: "Ping An Finance Centre, Shenzhen",
            desc: "Mit 599 Metern eines der höchsten Gebäude der Welt. Die Aussichtsplattform „Free Sky“ im 116. Stock erreicht man per Hochgeschwindigkeitsaufzug – ganz ohne Treppen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Pingan_International_Finance_Center2020.jpg/1280px-Pingan_International_Finance_Center2020.jpg",
            lat: 22.5370, lng: 114.0500, stroller: "yes",
            badges: ["Aufzug bis 116. Stock", "Ticket vor Ort"] },
          { name: "Shenzhen Civic Center", cn: "深圳市民中心", mapsName: "Shenzhen Civic Center, Futian",
            desc: "Das wellenförmige Dach des Bürgerzentrums ist Shenzhens architektonisches Wahrzeichen. Der weite Platz davor ist komplett eben – abends stimmungsvoll beleuchtet.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Night_of_Civic_Center_Shenzhen_from_Lianhua_Mountain.jpg/1280px-Night_of_Civic_Center_Shenzhen_from_Lianhua_Mountain.jpg",
            lat: 22.5460, lng: 114.0580, stroller: "yes",
            badges: ["Abends beleuchtet", "Komplett eben"] },
          { name: "OCT-LOFT Kreativviertel", cn: "华侨城创意文化园", mapsName: "OCT-LOFT, Nanshan, Shenzhen",
            desc: "Ehemalige Fabrikhallen, heute Galerien, Designläden und Cafés unter alten Bäumen. Entspannt, schattig und angenehm unaufgeregt – die schönste Kaffeepause der Stadt.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/OCTshenzhen2020.jpg/1280px-OCTshenzhen2020.jpg",
            lat: 22.5420, lng: 113.9880, stroller: "yes",
            badges: ["Cafés & Galerien", "Viel Schatten"] },
          { name: "Window of the World", cn: "世界之窗", mapsName: "Window of the World, Shenzhen",
            desc: "Themenpark mit Miniaturnachbildungen weltberühmter Bauwerke – vom Eiffelturm bis zu den Pyramiden. Kitschig, aber bei Familien beliebt. Nur, wenn Zeit bleibt.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/WINDOWS_OF_THE_WORLD_SHENZHEN_%2813%29.jpg/1280px-WINDOWS_OF_THE_WORLD_SHENZHEN_%2813%29.jpg",
            lat: 22.5390, lng: 113.9740, stroller: "yes",
            badges: ["Optional", "Eintritt kostenpflichtig"],
            inRoute: false },
        ],
        restaurants: [
          { name: "Dim Sum in Futian", mapsName: "dim sum restaurant Futian Shenzhen",
            desc: "Shenzhen liegt in Guangdong – dem Heimatland des Dim Sum. Rund um den Shopping Park gibt es zahlreiche kantonesische Häuser mit gedämpften Köstlichkeiten.",
            lat: 22.5390, lng: 114.0530, price: "10–20 € / Person",
            badges: ["Kantonesisch", "Gedämpft"] },
          { name: "Reisnudel-Küche (米粉)", mapsName: "rice noodle restaurant Shenzhen",
            desc: "Reisnudelsuppen sind in Südchina überall zu finden, leicht bekömmlich und von Natur aus glutenfrei – Vorsicht nur bei der Sojasauce, die Weizen enthält.",
            lat: 22.5400, lng: 114.0510, price: "4–10 € / Portion",
            badges: ["Glutenfrei möglich", "Leicht", "Gut fürs Baby"] },
          { name: "OCT-LOFT Cafés & Bowls", mapsName: "cafe OCT-LOFT Shenzhen",
            desc: "Im Kreativviertel gibt es moderne Cafés mit Salaten, Bowls und gutem Kaffee – die westlichste und leichteste Option der Stadt.",
            lat: 22.5422, lng: 113.9885, price: "8–18 € / Gericht",
            badges: ["Gesund", "Bowls", "Guter Kaffee"] },
        ],
      },
    ],
  },

  /* ========================= GUILIN ========================= */
  {
    id: "guilin",
    name: "Guilin",
    cn: "桂林",
    country: "Provinz Guangxi",
    dateLabel: "13.–15. September",
    dayLabel: "Tag 5–7",
    nights: 2,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/87318-Li-River.jpg/1280px-87318-Li-River.jpg",
    summary: "„Guilins Landschaft ist die schönste unter dem Himmel“ – Karstberge wie aus einem Tuschgemälde, Seen mitten in der Stadt und der Li-Fluss.",
    highlights: ["Elefantenrüssel-Berg", "Li-Fluss", "Zwei Seen"],
    hotel: {
      name: "Shangri-La Guilin",
      address: "No. 111, Huancheng North 2nd Road, Qixing District",
      mapsName: "Shangri-La Guilin, Huancheng North Road",
      lat: 25.29806, lng: 110.30289,
      price: "64–172 € / Nacht",
      why: "Die beste Babybett-Bestätigung der Reise: kostenlos für Kinder bis 3 Jahre. Große Gartenanlage direkt am Li-Fluss, Innen- und Außenpool, Kinderspielbereich mit Rutsche.",
      transfer: "Bahnhof Guilin North ca. 5,5 km · Zentrum per Taxi wenige Minuten",
    },
    intro: "Nach den zwei Großstädten wird es grün und langsam. Guilin ist deutlich entspannter – ideal, um mit dem Baby durchzuatmen, bevor es weiter nach Norden geht.",
    zones: [
      {
        id: "gl-stadt",
        tag: "Tag-Idee · Stadt & Seen",
        title: "Guilin Stadt – Seen, Pagoden & Höhle",
        summary: "Die Zwei-Flüsse-Vier-Seen-Promenade ist eben und autofrei, dazu der berühmte Elefantenrüssel-Berg und die bunt beleuchtete Schilfrohrflöten-Höhle.",
        walkFromHotel: "Promenade fußläufig, Höhle per Taxi",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Xiangshan_Scenic_Area_89468-Guilin_%2831130832628%29.jpg/1280px-Xiangshan_Scenic_Area_89468-Guilin_%2831130832628%29.jpg",
        transportNote: "Die Seenpromenade im Zentrum ist flach, gepflastert und autofrei – die kinderwagenfreundlichste Strecke der ganzen Reise. Taxis sind in Guilin günstig (meist unter 4 €), für die Schilfrohrflöten-Höhle im Nordwesten braucht ihr eins.",
        route: { fromHotel: false, mode: "walking" },
        sights: [
          { name: "Elefantenrüssel-Berg", cn: "象鼻山", mapsName: "Elephant Trunk Hill, Guilin",
            desc: "Wahrzeichen der Stadt: ein Felsen, der aussieht wie ein Elefant, der seinen Rüssel ins Wasser taucht. Der Blick vom Uferpark gegenüber ist kostenlos und mindestens so schön.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Xiangshan_Scenic_Area_89468-Guilin_%2831130832628%29.jpg/1280px-Xiangshan_Scenic_Area_89468-Guilin_%2831130832628%29.jpg",
            lat: 25.2600, lng: 110.2960, stroller: "careful",
            badges: ["Park kostenpflichtig", "Blick von außen gratis"] },
          { name: "Sonnen- & Mondpagode am Shanhu-See", cn: "日月双塔", mapsName: "Sun and Moon Pagodas, Guilin",
            desc: "Zwei Pagoden direkt am See – die goldene Sonnenpagode ist abends spektakulär beleuchtet. Die Uferwege ringsum sind flach und perfekt für einen Abendspaziergang.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/87318-Li-River.jpg/1280px-87318-Li-River.jpg",
            lat: 25.2740, lng: 110.2930, stroller: "yes",
            badges: ["Abends beleuchtet", "Uferweg eben"] },
          { name: "Sieben-Sterne-Park", cn: "七星公园", mapsName: "Seven Star Park, Guilin",
            desc: "Größter Park der Stadt mit Karstgipfeln, alten Brücken und einem kleinen Zoo mit Pandas. Weitläufig und schattig – gut für einen halben Tag mit Kind.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Camel_Hill_Guilin.jpg/1280px-Camel_Hill_Guilin.jpg",
            lat: 25.2760, lng: 110.3160, stroller: "yes",
            badges: ["Pandas", "Große Wege", "Nahe Hotel"] },
          { name: "Schilfrohrflöten-Höhle", cn: "芦笛岩", mapsName: "Reed Flute Cave, Guilin",
            desc: "Riesige Tropfsteinhöhle, bunt illuminiert – für Kinder faszinierend. Der Weg hindurch hat allerdings viele Stufen und feuchte Abschnitte: hier braucht ihr die Trage.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Stone_curtains_on_display_at_Reed_Flute_Cave.JPG/1280px-Stone_curtains_on_display_at_Reed_Flute_Cave.JPG",
            lat: 25.2940, lng: 110.2540, stroller: "no",
            badges: ["Viele Stufen → Trage", "Rutschig", "Kühl – Jacke mit"] },
        ],
        restaurants: [
          { name: "Guilin Reisnudeln (桂林米粉)", mapsName: "Guilin rice noodles restaurant, Guilin",
            desc: "Das Nationalgericht der Stadt und überall zu finden: Reisnudeln in würziger Brühe, oft schon zum Frühstück. Reisnudeln sind von Natur aus glutenfrei.",
            lat: 25.2760, lng: 110.2950, price: "1–4 € / Portion",
            badges: ["Lokale Spezialität", "Glutenfrei (Nudeln)", "Sehr günstig"] },
          { name: "Zhengyang Fußgängerzone", mapsName: "Zhengyang Pedestrian Street, Guilin",
            desc: "Autofreie Straße im Zentrum mit Restaurants, Snackständen und Obst. Bequem mit Kinderwagen und gut, wenn jeder etwas anderes möchte.",
            lat: 25.2755, lng: 110.2975, price: "5–15 € / Person",
            badges: ["Autofrei", "Große Auswahl"] },
          { name: "Hotel-Restaurants am Li-Fluss", mapsName: "restaurant Li River Guilin",
            desc: "Am Flussufer und in den größeren Hotels bekommt ihr verlässlich gedämpften Fisch, Gemüse und Reisgerichte – die leichteste und babytauglichste Küche vor Ort.",
            lat: 25.2900, lng: 110.3020, price: "12–25 € / Gericht",
            badges: ["Gesund", "Gedämpft", "Verlässliche Hygiene"] },
        ],
      },
      {
        id: "gl-lifluss",
        tag: "Tag-Idee · Bootstour",
        title: "Li-Fluss – die berühmteste Landschaft Chinas",
        summary: "Die Fahrt zwischen den Karstbergen ist das Motiv auf dem 20-Yuan-Schein. Vier Stunden gleitet das Schiff durch eine Tuschezeichnung.",
        walkFromHotel: "Transfer zum Anleger ~40 Min.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Li_River_at_Xingping_1.jpg/1280px-Li_River_at_Xingping_1.jpg",
        transportNote: "Die große Kreuzfahrt Guilin–Yangshuo dauert ca. 4 Stunden und endet praktischerweise genau dort, wo ihr als Nächstes hinwollt. Mit Baby könnt ihr also Bootsfahrt und Weiterreise verbinden – Gepäck wird meist per Transfer nachgebracht. Die Schiffe haben Toiletten, Sitzplätze im Schatten und ein Sonnendeck.",
        route: { fromHotel: false, mode: "transit" },
        sights: [
          { name: "Li-Fluss Kreuzfahrt", cn: "漓江", mapsName: "Li River Cruise Mopanshan Pier, Guilin",
            desc: "Vier Stunden durch die berühmteste Flusslandschaft Chinas: Wasserbüffel am Ufer, Bambushaine und Hunderte Karstgipfel. Mit Baby entspannt, weil man einfach sitzt und schaut.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/87318-Li-River.jpg/1280px-87318-Li-River.jpg",
            lat: 25.1600, lng: 110.3600, stroller: "careful",
            badges: ["Ca. 4 Stunden", "Vorab buchen", "Schatten & Toiletten an Bord"] },
          { name: "Xingping", cn: "兴坪", mapsName: "Xingping Ancient Town, Yangshuo",
            desc: "Kleines altes Städtchen am Fluss, hier liegt der Blick vom 20-Yuan-Schein. Wer keine ganze Kreuzfahrt machen will, kann von hier eine kurze Bambusfloß-Tour unternehmen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Li_River_at_Xingping_1.jpg/1280px-Li_River_at_Xingping_1.jpg",
            lat: 24.9370, lng: 110.5150, stroller: "careful",
            badges: ["20-Yuan-Blick", "Kopfsteinpflaster"] },
        ],
        restaurants: [
          { name: "Bordverpflegung / Lunchbox", mapsName: "Li River cruise boat Guilin",
            desc: "Auf den Kreuzfahrtschiffen gibt es einfache Lunchboxen mit Reis und Gemüse. Nehmt für das Baby eigene Snacks und Wasser mit – das ist entspannter.",
            lat: 25.1600, lng: 110.3600, price: "im Ticket oder 5–12 €",
            badges: ["Eigene Snacks mitnehmen"] },
          { name: "Fischrestaurants in Xingping", mapsName: "restaurant Xingping Yangshuo",
            desc: "Am Ufer gibt es kleine Lokale mit frischem Flussfisch, gedämpft oder gegrillt, dazu Reis und Gemüse – frisch, leicht und meist glutenfrei.",
            lat: 24.9372, lng: 110.5155, price: "8–18 € / Gericht",
            badges: ["Frischer Fisch", "Glutenfrei möglich"] },
        ],
      },
    ],
  },

  /* ========================= YANGSHUO ========================= */
  {
    id: "yangshuo",
    name: "Yangshuo",
    cn: "阳朔",
    country: "Provinz Guangxi",
    dateLabel: "15.–17. September",
    dayLabel: "Tag 7–9",
    nights: 2,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/1_guilin_yangshuo_2017.jpg/1280px-1_guilin_yangshuo_2017.jpg",
    summary: "Karstberge, Reisfelder und der türkise Yulong-Fluss. Der ruhigste Teil der Reise – hier gibt es nichts abzuhaken, nur zu genießen.",
    highlights: ["Yulong-Fluss", "West Street", "Mondberg"],
    hotel: {
      name: "Yangshuo Riverside Resort Hotel",
      address: "North Side of Gongnong Bridge, Gaotian Town",
      mapsName: "Yangshuo Riverside Resort Hotel, Gaotian",
      lat: 24.74013, lng: 110.48384,
      price: "89–213 € / Nacht",
      why: "Gitterbett kostenlos für alle Zimmertypen bestätigt. Suiten mit 65–95 m² geben einem krabbelnden Baby viel Platz. Ruhige Lage direkt am Yulong-Fluss mit Bergblick.",
      transfer: "Zentrum Yangshuo ca. 10 Min. mit Taxi · Bahnhof Yangshuo 36 km (Bus/Taxi)",
    },
    intro: "Zwei Nächte zum Runterkommen. Yangshuo ist der Ort, an dem viele China-Reisende am liebsten länger bleiben würden – Landschaft statt Sightseeing.",
    zones: [
      {
        id: "ys-yulong",
        tag: "Tag-Idee · Natur",
        title: "Yulong-Fluss, Mondberg & Reisfelder",
        summary: "Bambusfloß auf dem stillen Yulong-Fluss, die Zehn-Meilen-Galerie zwischen den Karstbergen und der Mondberg mit seinem natürlichen Felsbogen.",
        walkFromHotel: "Direkt vor der Hoteltür bzw. kurze Taxifahrt",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Yulong.JPG/1280px-Yulong.JPG",
        transportNote: "Das Hotel liegt mitten in dieser Zone. Die „Zehn-Meilen-Galerie“ ist eine ruhige Landstraße zwischen Karstbergen – klassisch mit dem Fahrrad, mit Baby aber besser per E-Roller-Taxi oder Taxi. Bambusflöße auf dem Yulong sind ruhig und flach; Schwimmwesten gibt es, prüft aber, ob eine für das Baby passt.",
        route: { fromHotel: true, mode: "walking" },
        sights: [
          { name: "Yulong-Fluss Bambusfloß", cn: "遇龙河", mapsName: "Yulong River bamboo raft, Yangshuo",
            desc: "Auf einem Bambusfloß gemächlich zwischen Karstbergen und Reisfeldern treiben – ruhiger und schöner als der große Li-Fluss. Die Flöße fahren langsam und über flaches Wasser.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Yulong.JPG/1280px-Yulong.JPG",
            lat: 24.7400, lng: 110.4840, stroller: "no",
            badges: ["Trage nötig", "Schwimmweste prüfen", "Sonnenschutz!"] },
          { name: "Zehn-Meilen-Galerie", cn: "十里画廊", mapsName: "Ten Mile Gallery, Yangshuo",
            desc: "Landschaftsstraße durch das schönste Karstpanorama der Region, gesäumt von Feldern und Bergen. Mehrere Aussichtspunkte lassen sich bequem per Taxi abfahren.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/1_guilin_yangshuo_2017.jpg/1280px-1_guilin_yangshuo_2017.jpg",
            lat: 24.7500, lng: 110.4700, stroller: "careful",
            badges: ["Per Taxi abfahrbar", "Viele Fotostopps"] },
          { name: "Mondberg", cn: "月亮山", mapsName: "Moon Hill, Yangshuo",
            desc: "Berg mit einem natürlichen, mondförmigen Loch im Fels. Der Aufstieg sind rund 800 Stufen – mit Baby nicht machbar, aber der Blick von unten ist ebenfalls beeindruckend.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Moonmtyangshuo.jpg/1280px-Moonmtyangshuo.jpg",
            lat: 24.7220, lng: 110.4590, stroller: "no",
            badges: ["800 Stufen hinauf", "Von unten gut sichtbar"] },
          { name: "West Street", cn: "西街", mapsName: "West Street, Yangshuo",
            desc: "Die lebhafte Fußgängerstraße im Zentrum mit Cafés, Läden und Garküchen. Abends bunt beleuchtet und quirlig; tagsüber deutlich ruhiger und angenehmer mit Kinderwagen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/1_guilin_yangshuo_2017.jpg/1280px-1_guilin_yangshuo_2017.jpg",
            lat: 24.7780, lng: 110.4960, stroller: "careful",
            badges: ["Autofrei", "Abends sehr voll", "Kopfsteinpflaster"] },
        ],
        restaurants: [
          { name: "Bierfisch (啤酒鱼)", mapsName: "beer fish restaurant West Street Yangshuo",
            desc: "Die lokale Spezialität: frischer Flussfisch, geschmort in Bier mit Gemüse und Chili. In fast jedem Restaurant an der West Street zu bekommen.",
            lat: 24.7778, lng: 110.4958, price: "10–20 € / Gericht",
            badges: ["Lokale Spezialität", "Zum Teilen"] },
          { name: "Cafés an der West Street", mapsName: "cafe West Street Yangshuo",
            desc: "Yangshuo ist seit Jahrzehnten bei Rucksackreisenden beliebt – entsprechend gibt es westliche Cafés mit Frühstück, Obstsalat, Smoothies und Kaffee.",
            lat: 24.7782, lng: 110.4962, price: "5–14 € / Gericht",
            badges: ["Westliches Frühstück", "Gesund", "Obst & Smoothies"] },
          { name: "Hotel-Restaurant am Fluss", mapsName: "Yangshuo Riverside Resort restaurant",
            desc: "Nach einem Tag draußen ist das Restaurant im eigenen Resort mit Baby am entspanntesten: ruhig, sicher, mit Blick auf die Karstberge.",
            lat: 24.7402, lng: 110.4840, price: "12–25 € / Gericht",
            badges: ["Ruhig", "Ideal mit Baby", "Bergblick"] },
        ],
      },
    ],
  },

  /* ========================= XI'AN ========================= */
  {
    id: "xian",
    name: "Xi'an",
    cn: "西安",
    country: "Provinz Shaanxi",
    dateLabel: "17.–20. September",
    dayLabel: "Tag 9–12",
    nights: 3,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/City_wall_of_Xi%27an_51550-Xian_%2827959363326%29.jpg/1280px-City_wall_of_Xi%27an_51550-Xian_%2827959363326%29.jpg",
    summary: "Startpunkt der Seidenstraße und Heimat der Terrakotta-Armee. Eine komplett erhaltene Stadtmauer umschließt die Altstadt – Geschichte zum Anfassen.",
    highlights: ["Terrakotta-Armee", "Stadtmauer", "Muslimisches Viertel"],
    hotel: {
      name: "Grand Mercure Xi'an on Renmin Square",
      address: "No. 319 Dongxin Street, Xincheng District",
      mapsName: "Grand Mercure Xi'an on Renmin Square, Dongxin Street",
      lat: 34.26703, lng: 108.95413,
      price: "39–105 € / Nacht",
      why: "Familiensuiten mit 60–100 m². Liegt innerhalb der Ming-Stadtmauer auf einem weitläufigen, autofreien Parkgelände – mit Kinderwagen angenehmer als jede Hauptstraßenlage.",
      transfer: "Metro Wulukou 600 m (Linien 1 & 4) · Linie 4 umsteigefrei zum Bahnhof Xi'an North (~31 Min.)",
    },
    intro: "Der Flug bringt euch aus den grünen Karstbergen ins trockene Nordchina. Xi'an ist kompakt: fast alles liegt in oder direkt an der Stadtmauer.",
    zones: [
      {
        id: "xa-terrakotta",
        tag: "Tag-Idee · Weltwunder",
        title: "Terrakotta-Armee & Huaqing-Palast",
        summary: "8.000 lebensgroße Tonkrieger bewachen seit 2.200 Jahren das Grab des ersten Kaisers. Das mit Abstand größte Highlight der ganzen Reise.",
        walkFromHotel: "Bus/Taxi ca. 1 Std. nach Osten",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/51714-Terracota-Army.jpg/1280px-51714-Terracota-Army.jpg",
        transportNote: "Die Terrakotta-Armee liegt ca. 40 km östlich der Stadt. Bequem: Taxi/Didi (~45–60 Min.) oder Touristenbus Linie 5 (306) vom Bahnhof Xi'an. Tickets vorab online buchen. Planung mit Baby: Die Hallen sind riesig und man läuft viel – Kinderwagen ist erlaubt, in Halle 1 wird es aber sehr voll. Früh morgens gehen!",
        route: { fromHotel: false, mode: "transit" },
        sights: [
          { name: "Terrakotta-Armee", cn: "兵马俑", mapsName: "Terracotta Army Museum, Xi'an",
            desc: "Rund 8.000 individuell gestaltete Tonkrieger, Pferde und Wagen – jedes Gesicht ist anders. Drei überdachte Hallen, Halle 1 ist die spektakulärste. Plant mindestens 3 Stunden ein.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/51714-Terracota-Army.jpg/1280px-51714-Terracota-Army.jpg",
            lat: 34.3853, lng: 109.2784, stroller: "careful",
            badges: ["Tickets vorab!", "Früh hingehen", "Viel Laufen", "3+ Stunden"],
            ticketUrl: "https://www.bmy.com.cn/" },
          { name: "Huaqing-Palast & Thermalquellen", cn: "华清池", mapsName: "Huaqing Palace, Lintong, Xi'an",
            desc: "Kaiserliche Thermalbadanlage am Fuß des Li-Bergs, berühmt für die Liebesgeschichte von Kaiser Xuanzong und Yang Guifei. Liegt auf dem Weg zur Terrakotta-Armee.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Huaqingchi_1.JPG/1280px-Huaqingchi_1.JPG",
            lat: 34.3620, lng: 109.2130, stroller: "careful",
            badges: ["Auf dem Weg", "Gärten eben", "Einzelne Treppen"] },
        ],
        restaurants: [
          { name: "Restaurants am Museumsgelände", mapsName: "restaurant Terracotta Army Museum Xi'an",
            desc: "Am Besucherzentrum gibt es mehrere einfache Restaurants und Snackstände. Nicht großartig, aber praktisch – mit Baby ist eine Pause vor Ort wertvoller als die perfekte Küche.",
            lat: 34.3850, lng: 109.2770, price: "8–18 € / Gericht",
            badges: ["Praktisch", "Wickelmöglichkeit im Besucherzentrum"] },
          { name: "Nudelsuppen in Lintong", mapsName: "noodle restaurant Lintong Xi'an",
            desc: "Shaanxi ist Nudel-Land. Achtung bei Glutenunverträglichkeit: Die berühmten Biang-Biang- und Weizennudeln enthalten Gluten – fragt gezielt nach Reisnudeln (米粉).",
            lat: 34.3800, lng: 109.2200, price: "3–9 € / Portion",
            badges: ["Achtung: Weizennudeln", "Nach 米粉 fragen"] },
        ],
      },
      {
        id: "xa-stadtmauer",
        tag: "Tag-Idee · Altstadt",
        title: "Stadtmauer, Glockenturm & Muslimisches Viertel",
        summary: "Auf der 14 km langen Ming-Stadtmauer um die Altstadt, dann Glocken- und Trommelturm und das duftende Muslimische Viertel mit seinen Garküchen.",
        walkFromHotel: "Alles fußläufig bzw. 1–2 Metro-Stationen",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Xian_walls.jpg/1280px-Xian_walls.jpg",
        transportNote: "Euer Hotel liegt innerhalb der Stadtmauer – diese Zone ist eure Nachbarschaft. Auf die Mauer geht es per Treppe oder Aufzug (am Südtor vorhanden, vorher erfragen). Oben ist die Mauer 12–14 m breit und komplett eben: eine der schönsten Kinderwagen-Strecken überhaupt.",
        route: { fromHotel: true, mode: "walking" },
        sights: [
          { name: "Xi'aner Stadtmauer", cn: "西安城墙", mapsName: "Xi'an City Wall South Gate, Xi'an",
            desc: "Die besterhaltene Stadtmauer Chinas, 14 km lang und oben breit wie eine Straße. Man kann laufen, Fahrräder oder E-Carts mieten. Der Blick über die Altstadt ist grandios.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Xian_walls.jpg/1280px-Xian_walls.jpg",
            lat: 34.2530, lng: 108.9450, stroller: "careful",
            badges: ["Oben komplett eben", "Aufzug am Südtor erfragen", "E-Cart mietbar"],
            ticketUrl: "https://www.xaccw.com/" },
          { name: "Glockenturm", cn: "钟楼", mapsName: "Bell Tower of Xi'an",
            desc: "Der geografische Mittelpunkt der Altstadt aus dem 14. Jahrhundert, abends golden beleuchtet. Der Zugang erfolgt durch eine Unterführung; hinauf führen steile Stufen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/China_%28Xian%29_BellTower_at_night_%2826387646208%29.jpg/1280px-China_%28Xian%29_BellTower_at_night_%2826387646208%29.jpg",
            lat: 34.2610, lng: 108.9430, stroller: "careful",
            badges: ["Abends beleuchtet", "Hinauf: steile Stufen", "Unterführung zum Eingang"] },
          { name: "Trommelturm", cn: "鼓楼", mapsName: "Drum Tower of Xi'an",
            desc: "Gegenstück zum Glockenturm und Eingangstor zum Muslimischen Viertel. Mehrmals täglich gibt es Trommelvorführungen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Xian_drum_tower_2006.JPG/1280px-Xian_drum_tower_2006.JPG",
            lat: 34.2620, lng: 108.9390, stroller: "careful",
            badges: ["Trommel-Vorführungen", "Tor zum Muslim Quarter"] },
          { name: "Muslimisches Viertel", cn: "回民街", mapsName: "Muslim Quarter, Xi'an",
            desc: "Ein Gassenlabyrinth voller Garküchen, Gewürze und Gedränge – das kulinarische Herz Xi'ans. Sehr voll und eng: abends mit Baby lieber die Trage nehmen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Xian_2006_6-63.jpg/1280px-Xian_2006_6-63.jpg",
            lat: 34.2660, lng: 108.9390, stroller: "no",
            badges: ["Sehr eng & voll", "Trage empfohlen", "Tagsüber ruhiger"] },
          { name: "Große Moschee", cn: "西安大清真寺", mapsName: "Great Mosque of Xi'an",
            desc: "Über 1.200 Jahre alt und ganz im chinesischen Stil mit Pagoden und Gärten gebaut – von außen kaum als Moschee erkennbar. Eine ruhige Oase mitten im Trubel.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Xian_Mosque3.jpg/1280px-Xian_Mosque3.jpg",
            lat: 34.2650, lng: 108.9370, stroller: "careful",
            badges: ["Ruhige Oase", "Eintritt", "Schultern bedecken"] },
        ],
        restaurants: [
          { name: "Roujiamo (肉夹馍) – „chinesischer Burger“", mapsName: "Roujiamo Muslim Quarter Xi'an",
            desc: "Geschmortes Fleisch in einem knusprigen Fladenbrot – Xi'ans berühmtester Snack, überall im Muslimischen Viertel. Achtung: enthält Weizen.",
            lat: 34.2662, lng: 108.9392, price: "1–4 € / Stück",
            badges: ["Street Food", "Enthält Weizen"] },
          { name: "Liangpi (凉皮) – kalte Reisnudeln", mapsName: "Liangpi Xi'an",
            desc: "Kalte, glatte Nudeln aus Reismehl mit Gurke, Sesam und Chiliöl – erfrischend und meist glutenfrei. Fragt nach der Reisvariante (米皮), nicht der Weizenvariante.",
            lat: 34.2658, lng: 108.9388, price: "2–5 € / Portion",
            badges: ["Erfrischend", "Reisvariante glutenfrei", "Vegetarisch"] },
          { name: "Dumpling-Restaurants am Glockenturm", mapsName: "dumpling restaurant Bell Tower Xi'an",
            desc: "Xi'an ist berühmt für Dumpling-Bankette mit Dutzenden Sorten. Sitzrestaurants rund um den Glockenturm sind klimatisiert und mit Kinderwagen gut machbar.",
            lat: 34.2615, lng: 108.9425, price: "12–25 € / Person",
            badges: ["Klimatisiert", "Familientauglich", "Viele Sorten"] },
        ],
      },
      {
        id: "xa-pagode",
        tag: "Tag-Idee · Ruhiger Süden",
        title: "Wildgans-Pagode & Shaanxi-Museum",
        summary: "Die Große Wildgans-Pagode aus dem 7. Jahrhundert mit weitläufigen Parks und Chinas beeindruckendstes Provinzmuseum – ein ruhigerer, kühlerer Tag.",
        walkFromHotel: "Metro Linie 4 nach Süden, ~20 Min.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Giant_Wild_Goose_Pagoda.jpg/1280px-Giant_Wild_Goose_Pagoda.jpg",
        transportNote: "Mit der Metro Linie 4 vom Hotel direkt in den Süden. Die Parkanlagen rund um die Pagode sind weitläufig, eben und schattig – ideal, wenn das Baby im Kinderwagen schlafen soll. Der Nordplatz hat abends eine große Musik-Wasserfontänen-Show.",
        route: { fromHotel: false, mode: "transit" },
        sights: [
          { name: "Große Wildgans-Pagode", cn: "大雁塔", mapsName: "Giant Wild Goose Pagoda, Xi'an",
            desc: "652 erbaut, um buddhistische Schriften aus Indien zu beherbergen. Die Parks ringsum sind kostenlos, weitläufig und eben; der Aufstieg in die Pagode selbst geht über enge Treppen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Giant_Wild_Goose_Pagoda.jpg/1280px-Giant_Wild_Goose_Pagoda.jpg",
            lat: 34.2190, lng: 108.9640, stroller: "careful",
            badges: ["Park kostenlos", "Aufstieg: enge Treppen", "Abends Wassershow"] },
          { name: "Shaanxi-Geschichtsmuseum", cn: "陕西历史博物馆", mapsName: "Shaanxi History Museum, Xi'an",
            desc: "Eines der besten Museen Chinas mit über 370.000 Objekten aus 3.000 Jahren. Klimatisiert und barrierefrei – die perfekte Zuflucht an einem heißen Nachmittag.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Shaanxi_History_Museum.jpg/1280px-Shaanxi_History_Museum.jpg",
            lat: 34.2220, lng: 108.9540, stroller: "yes",
            badges: ["Eintritt frei (Reservierung!)", "Klimatisiert", "Barrierefrei"],
            ticketUrl: "https://www.sxhm.com/" },
        ],
        restaurants: [
          { name: "Cafés am Pagodenplatz", mapsName: "cafe Giant Wild Goose Pagoda Xi'an",
            desc: "Rund um die Pagode gibt es moderne Cafés und Teehäuser mit Klimaanlage – gut für eine lange Pause zwischen zwei Programmpunkten.",
            lat: 34.2195, lng: 108.9635, price: "5–15 € / Person",
            badges: ["Klimatisiert", "Ruhig"] },
          { name: "Gedämpfte Küche & Gemüse", mapsName: "steamed vegetarian restaurant Xi'an",
            desc: "Neben den deftigen Nudeln bietet Xi'an auch leichte gedämpfte Gerichte, Gemüse und Suppen – bekömmlicher, wenn der Magen eine Pause braucht.",
            lat: 34.2200, lng: 108.9600, price: "8–18 € / Gericht",
            badges: ["Gesund", "Gedämpft", "Vegetarisch möglich"] },
        ],
      },
    ],
  },

  /* ========================= PEKING ========================= */
  {
    id: "peking",
    name: "Peking",
    cn: "北京",
    country: "Hauptstadt",
    dateLabel: "20.–24. September",
    dayLabel: "Tag 12–16",
    nights: 4,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/The_Forbidden_City_-_View_from_Coal_Hill.jpg/1280px-The_Forbidden_City_-_View_from_Coal_Hill.jpg",
    summary: "Verbotene Stadt, Große Mauer, Himmelstempel: die dichteste Ansammlung von Weltwundern der Reise. Dazu Hutongs und Pandas im Zoo.",
    highlights: ["Verbotene Stadt", "Große Mauer", "Himmelstempel"],
    hotel: {
      name: "Park Plaza Beijing Wangfujing",
      address: "No. 97 Jinbao Street, Dongcheng District",
      mapsName: "Park Plaza Beijing Wangfujing, Jinbao Street",
      lat: 39.9146, lng: 116.4120,
      price: "55–190 € / Nacht",
      why: "Babybett kostenlos für Kinder bis 2 Jahre. Familienzimmer mit zwei Schlafzimmern (60 m²) und Familiensuite mit 90 m². Badewanne Standard – praktisch fürs Baby-Bad.",
      transfer: "Metro Dengshikou 300 m (Linie 5) · Verbotene Stadt ca. 18 Min. zu Fuß",
    },
    intro: "Vier volle Tage – und trotzdem knapp. Nehmt euch pro Tag nur eine Zone vor: Peking ist riesig, und die Wege zwischen den Sehenswürdigkeiten sind lang.",
    zones: [
      {
        id: "bj-verbotenestadt",
        tag: "Tag-Idee · Kaiserliches Peking",
        title: "Verbotene Stadt & Tian'anmen",
        summary: "Der größte Palastkomplex der Welt mit 980 Gebäuden, davor der monumentale Tian'anmen-Platz und dahinter der Aussichtshügel Jingshan.",
        walkFromHotel: "Ca. 18 Min. zu Fuß bzw. 1 Metro-Station",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/The_Forbidden_City_-_View_from_Coal_Hill.jpg/1280px-The_Forbidden_City_-_View_from_Coal_Hill.jpg",
        transportNote: "WICHTIG: Für die Verbotene Stadt und den Tian'anmen-Platz braucht ihr eine Online-Reservierung mit Reisepass – oft Tage im Voraus ausgebucht. Bucht das als Erstes! Der Rundgang geht immer von Süd nach Nord (Eingang Meridian-Tor, Ausgang Tor der Göttlichen Kraft) und ist etwa 2–3 km lang. Danach liegt Jingshan direkt gegenüber dem Nordausgang.",
        route: { fromHotel: true, mode: "walking" },
        sights: [
          { name: "Tian'anmen-Platz", cn: "天安门广场", mapsName: "Tiananmen Square, Beijing",
            desc: "Einer der größten öffentlichen Plätze der Welt, komplett eben und weitläufig. Sicherheitskontrollen mit Passkontrolle am Eingang – plant Zeit ein.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Tiananmen_Square_%2854137047250%29.jpg/1280px-Tiananmen_Square_%2854137047250%29.jpg",
            lat: 39.9055, lng: 116.3976, stroller: "yes",
            badges: ["Reisepass mitnehmen!", "Sicherheitskontrolle", "Komplett eben"] },
          { name: "Verbotene Stadt", cn: "故宫", mapsName: "Forbidden City, Beijing",
            desc: "500 Jahre Kaiserresidenz: Höfe, Hallen und Dächer, so weit das Auge reicht. Rechnet 3–4 Stunden und rund 3 km Fußweg ein. Zwischen den Höfen gibt es überall flache Rampen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/The_Forbidden_City_-_View_from_Coal_Hill.jpg/1280px-The_Forbidden_City_-_View_from_Coal_Hill.jpg",
            lat: 39.9163, lng: 116.3972, stroller: "careful",
            badges: ["Reservierung Pflicht!", "Pass mitnehmen", "3–4 Std., ~3 km", "Montags meist zu"],
            ticketUrl: "https://gugong.ktmtech.cn/" },
          { name: "Jingshan-Park", cn: "景山公园", mapsName: "Jingshan Park, Beijing",
            desc: "Künstlicher Hügel direkt hinter der Verbotenen Stadt mit DEM Postkartenblick über die goldenen Dächer. Hinauf führen Stufen – mit Trage machbar, sonst unten im Park bleiben.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Jingshan_park.jpg/1280px-Jingshan_park.jpg",
            lat: 39.9250, lng: 116.3900, stroller: "no",
            badges: ["Bester Ausblick", "Stufen hinauf → Trage", "Direkt am Nordausgang"] },
        ],
        restaurants: [
          { name: "Peking-Ente bei Quanjude oder Da Dong", mapsName: "Quanjude Peking duck restaurant Beijing",
            desc: "Peking-Ente ist Pflichtprogramm. Quanjude ist die Traditionsadresse seit 1864, Da Dong die modernere, knusprigere Variante. Beide klimatisiert und familientauglich – reservieren!",
            lat: 39.9130, lng: 116.4100, price: "25–45 € / Person",
            badges: ["Klassiker", "Reservieren!", "Pfannkuchen enthalten Weizen"] },
          { name: "Wangfujing Snack Street", mapsName: "Wangfujing Snack Street, Beijing",
            desc: "Fußläufige Einkaufsstraße nahe dem Hotel mit Foodcourts in den Malls – klimatisiert, große Auswahl und mit Wickelräumen. Die pragmatische Wahl mit Baby.",
            lat: 39.9150, lng: 116.4080, price: "6–18 € / Gericht",
            badges: ["Nah am Hotel", "Klimatisiert", "Wickelraum"] },
          { name: "King's Joy / vegetarische Küche", mapsName: "vegetarian restaurant Beijing Dongcheng",
            desc: "Peking hat exzellente vegetarische Restaurants, oft in Tempelnähe: Gemüse, Pilze und Tofu, kunstvoll zubereitet. Deutlich leichter als Ente und Nudeln.",
            lat: 39.9400, lng: 116.4110, price: "20–40 € / Person",
            badges: ["Gesund", "Vegetarisch", "Glutenfrei auf Anfrage"] },
        ],
      },
      {
        id: "bj-mauer",
        tag: "Tag-Idee · Weltwunder",
        title: "Große Mauer bei Mutianyu",
        summary: "Der familienfreundlichste Mauerabschnitt: restauriert, weniger überlaufen als Badaling und mit Seilbahn hinauf – kein Aufstieg nötig.",
        walkFromHotel: "Ca. 1,5 Std. mit Auto/Bus nach Norden",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Great_Wall_of_China_July_2006.JPG/1280px-Great_Wall_of_China_July_2006.JPG",
        transportNote: "Mutianyu liegt ca. 70 km nordöstlich, Fahrzeit 1,5 Stunden. Am einfachsten mit privatem Fahrer für den Tag (~60–90 €) – mit Baby klar die beste Lösung, weil ihr Pausen selbst bestimmt. Nehmt die Seilbahn hinauf (kein Aufstieg!). Oben ist die Mauer allerdings steil und stufig: Trage ist Pflicht, der Kinderwagen bleibt unten im Auto.",
        route: { fromHotel: false, mode: "transit" },
        sights: [
          { name: "Große Mauer Mutianyu", cn: "慕田峪长城", mapsName: "Mutianyu Great Wall, Beijing",
            desc: "2,25 km restaurierte Mauer mit 22 Wachtürmen, eingebettet in bewaldete Berge. Die Seilbahn bringt euch direkt hinauf. Oben selbst ist die Mauer steil und voller Stufen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Great_Wall_of_China_July_2006.JPG/1280px-Great_Wall_of_China_July_2006.JPG",
            lat: 40.4319, lng: 116.5704, stroller: "no",
            badges: ["Trage zwingend!", "Seilbahn hinauf", "Sonnenschutz & Wasser", "Ganztags"],
            ticketUrl: "https://www.mutianyugreatwall.com/" },
        ],
        restaurants: [
          { name: "Restaurants am Mauerfuß", mapsName: "restaurant Mutianyu Great Wall",
            desc: "Am Besucherzentrum und im Dorf Mutianyu gibt es mehrere Restaurants mit chinesischer und westlicher Küche – der übliche Stopp nach dem Abstieg.",
            lat: 40.4270, lng: 116.5650, price: "10–25 € / Person",
            badges: ["Vor Ort", "Auch westliche Küche"] },
          { name: "Picknick & Proviant", mapsName: "supermarket Beijing Wangfujing",
            desc: "Nehmt Wasser, Obst und Babynahrung ausreichend mit – oben auf der Mauer gibt es nichts, und die Sonne ist im September noch kräftig.",
            lat: 39.9150, lng: 116.4080, price: "je nach Einkauf",
            badges: ["Vorher einkaufen", "Viel Wasser!"] },
        ],
      },
      {
        id: "bj-hutong",
        tag: "Tag-Idee · Altes Peking",
        title: "Himmelstempel, Hutongs & Lamatempel",
        summary: "Der perfekt runde Himmelstempel in seinem riesigen Park, dazu die alten Gassenviertel rund um den Houhai-See und der farbenprächtige Lamatempel.",
        walkFromHotel: "Metro; Hutongs teils fußläufig",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Temple_of_Heaven_20160323_01.jpg/1280px-Temple_of_Heaven_20160323_01.jpg",
        transportNote: "Der Himmelstempelpark ist morgens am schönsten – dann treffen sich dort Hunderte Pekinger zum Tai Chi, Tanzen und Kartenspielen. Die Hutongs sind flache, autoarme Gassen und gut mit Kinderwagen befahrbar, teils aber uneben gepflastert. Pekings Metro hat an großen Stationen Aufzüge, an kleinen nicht immer.",
        route: { fromHotel: false, mode: "transit" },
        sights: [
          { name: "Himmelstempel", cn: "天坛", mapsName: "Temple of Heaven, Beijing",
            desc: "Die perfekt runde Halle der Ernteopfer ist eines der schönsten Bauwerke Chinas. Der umgebende Park ist riesig, eben und schattig – morgens voller Leben.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Temple_of_Heaven_20160323_01.jpg/1280px-Temple_of_Heaven_20160323_01.jpg",
            lat: 39.8822, lng: 116.4066, stroller: "yes",
            badges: ["Morgens: Tai Chi", "Park eben & schattig", "Kombiticket"],
            ticketUrl: "https://www.tiantanpark.com/" },
          { name: "Houhai-See & Hutongs", cn: "后海", mapsName: "Houhai Lake, Beijing",
            desc: "Seenlandschaft mitten in der Stadt, umgeben von alten Gassenvierteln, Cafés und Weidenbäumen. Am Ufer entlangschieben und das alte Peking erleben.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Beijing_Houhai_lake_-_panoramio.jpg/1280px-Beijing_Houhai_lake_-_panoramio.jpg",
            lat: 39.9400, lng: 116.3830, stroller: "yes",
            badges: ["Uferweg eben", "Abends lebhaft", "Rikscha-Touren"] },
          { name: "Nanluoguxiang", cn: "南锣鼓巷", mapsName: "Nanluoguxiang, Beijing",
            desc: "Restaurierte Hutong-Gasse aus dem 13. Jahrhundert mit Läden, Snacks und Cafés. Sehr beliebt und entsprechend voll – die ruhigeren Seitengassen sind oft schöner.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/2016-09-04_Beijing_Nanluoguxiang_anagoria_23.jpg/1280px-2016-09-04_Beijing_Nanluoguxiang_anagoria_23.jpg",
            lat: 39.9370, lng: 116.4030, stroller: "careful",
            badges: ["Sehr voll", "Seitengassen ruhiger"] },
          { name: "Lamatempel (Yonghe)", cn: "雍和宫", mapsName: "Lama Temple Yonghegong, Beijing",
            desc: "Bedeutendster tibetisch-buddhistischer Tempel außerhalb Tibets, mit einer 18 m hohen Buddha-Statue aus einem einzigen Sandelholzstamm. Viel Weihrauch, mehrere Türschwellen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/65618-Beijing-Lama-Temple_%2828098480603%29.jpg/1280px-65618-Beijing-Lama-Temple_%2828098480603%29.jpg",
            lat: 39.9470, lng: 116.4110, stroller: "careful",
            badges: ["Hohe Türschwellen", "Viel Weihrauch", "Direkt an der Metro"] },
        ],
        restaurants: [
          { name: "Hutong-Cafés am Houhai", mapsName: "cafe Houhai hutong Beijing",
            desc: "In den Gassen rund um den See gibt es charmante kleine Cafés in alten Hofhäusern – ruhig, mit Innenhof und guter Kaffeequalität.",
            lat: 39.9395, lng: 116.3840, price: "5–15 € / Person",
            badges: ["Innenhöfe", "Ruhig"] },
          { name: "Jianbing & Baozi (Straßenfrühstück)", mapsName: "jianbing street food Beijing",
            desc: "Jianbing (herzhafter Crêpe) und gedämpfte Baozi sind das klassische Pekinger Frühstück, überall an Straßenständen. Günstig und frisch zubereitet.",
            lat: 39.9380, lng: 116.4020, price: "1–4 € / Portion",
            badges: ["Street Food", "Frisch", "Enthält Weizen"] },
          { name: "Gedämpfte Küche & Hot Pot mit Gemüse", mapsName: "hot pot restaurant Beijing Dongcheng",
            desc: "Hot Pot mit klarer Pilzbrühe und viel Gemüse ist eine überraschend leichte, gesunde Option – und jeder stellt sich selbst zusammen. Ideal bei Unverträglichkeiten.",
            lat: 39.9350, lng: 116.4060, price: "15–30 € / Person",
            badges: ["Gesund", "Selbst zusammenstellen", "Glutenfrei möglich"] },
        ],
      },
      {
        id: "bj-sommerpalast",
        tag: "Tag-Idee · Park & Pandas",
        title: "Sommerpalast, Zoo & Olympiapark",
        summary: "Der kaiserliche Sommerpalast am Kunming-See, Pandas im Pekinger Zoo und das Vogelnest-Stadion – der entspannteste Pekinger Tag.",
        walkFromHotel: "Metro nach Nordwesten, ~45 Min.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Longevity_Hill_of_the_Summer_Palace.jpg/1280px-Longevity_Hill_of_the_Summer_Palace.jpg",
        transportNote: "Der Sommerpalast liegt im Nordwesten (Metro Linie 4 bis Beigongmen). Die Uferwege am Kunming-See sind eben, der Langlebigkeits-Hügel dagegen steil. Tipp mit Baby: Nur das Seeufer und den Langen Korridor machen, den Hügel weglassen. Der Zoo mit den Pandas liegt auf dem Rückweg an derselben Linie.",
        route: { fromHotel: false, mode: "transit" },
        sights: [
          { name: "Sommerpalast", cn: "颐和园", mapsName: "Summer Palace, Beijing",
            desc: "Kaiserliche Gartenanlage rund um den Kunming-See mit dem 728 m langen, bemalten „Langen Korridor“. Die Uferwege sind eben; der Hügel dahinter ist steil.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Longevity_Hill_of_the_Summer_Palace.jpg/1280px-Longevity_Hill_of_the_Summer_Palace.jpg",
            lat: 39.9999, lng: 116.2755, stroller: "careful",
            badges: ["Seeufer eben", "Hügel steil", "Bootsfahrten", "Halber Tag"],
            ticketUrl: "https://www.summerpalace-china.com/" },
          { name: "Pekinger Zoo – Pandas", cn: "北京动物园", mapsName: "Beijing Zoo, Beijing",
            desc: "Riesenpandas mitten in der Stadt, dazu viele weitere Tiere. Der Zoo ist eben und komplett kinderwagentauglich – für einen 10 Monate alten Krabbler das größte Vergnügen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Gate_of_Beijing_Zoo_%2820210219172711%29.jpg/1280px-Gate_of_Beijing_Zoo_%2820210219172711%29.jpg",
            lat: 39.9390, lng: 116.3350, stroller: "yes",
            badges: ["Pandas!", "Komplett eben", "Ideal mit Baby"],
            ticketUrl: "http://www.beijingzoo.com/" },
          { name: "Olympiapark & Vogelnest", cn: "鸟巢", mapsName: "Beijing National Stadium Bird's Nest",
            desc: "Das Vogelnest-Stadion und der Wasserwürfel von 2008, verbunden durch eine weite, autofreie Promenade. Abends spektakulär beleuchtet und sehr entspannt zu schieben.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Beijing_China_Beijing-National-Stadium-01.jpg/1280px-Beijing_China_Beijing-National-Stadium-01.jpg",
            lat: 39.9928, lng: 116.3964, stroller: "yes",
            badges: ["Außen kostenlos", "Abends beleuchtet", "Autofrei"],
            inRoute: false },
        ],
        restaurants: [
          { name: "Restaurants am Sommerpalast-Nordtor", mapsName: "restaurant Summer Palace north gate Beijing",
            desc: "Rund um die Tore gibt es einfache Nudel- und Reisrestaurants sowie Snackstände – praktisch für die Mittagspause zwischen Palast und Zoo.",
            lat: 40.0010, lng: 116.2740, price: "6–16 € / Gericht",
            badges: ["Praktisch", "Einfach & schnell"] },
          { name: "Malls am Zoo / Xizhimen", mapsName: "shopping mall Xizhimen Beijing",
            desc: "Bei Xizhimen gibt es große klimatisierte Malls mit Foodcourts, Wickelräumen und Stillmöglichkeiten – mit Baby der verlässlichste Stopp.",
            lat: 39.9410, lng: 116.3490, price: "8–20 € / Gericht",
            badges: ["Klimatisiert", "Wickelraum", "Große Auswahl"] },
        ],
      },
    ],
  },

  /* ========================= SHANGHAI ========================= */
  {
    id: "shanghai",
    name: "Shanghai",
    cn: "上海",
    country: "Metropole am Huangpu",
    dateLabel: "24.–30. September",
    dayLabel: "Tag 16–22",
    nights: 6,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Bund_2.jpg/1280px-The_Bund_2.jpg",
    summary: "Kolonialfassaden am Bund gegenüber der futuristischen Skyline von Pudong. Der entspannte Abschluss – mit genug Zeit für Tagesausflüge per Schnellzug.",
    highlights: ["Der Bund", "Yu-Garten", "Wasserstadt Zhujiajiao"],
    hotel: {
      name: "Ascott Huaihai Road Shanghai, Xintiandi",
      address: "No. 282 Huaihai Middle Road, Huangpu District",
      mapsName: "Ascott Huaihai Road Shanghai Xintiandi",
      lat: 31.2258, lng: 121.4701,
      price: "110–250 € / Nacht",
      why: "Serviced Apartments mit voll ausgestatteter Küche und Waschmaschine – bei 6 Nächten mit Baby Gold wert (Fläschchen, Brei, Babywäsche). Gitterbett kostenlos bis 2 Jahre, beheizter Innenpool, 108–155 m² Wohnfläche.",
      transfer: "Metro Huangpi South Road 110 m (Linien 1 & 14) · Hongqiao Bahnhof ~35 Min.",
    },
    intro: "Sechs Nächte am Stück – kein Kofferpacken mehr. Das gibt euch Luft für Tagesausflüge und ruhige Tage. Das Mittherbstfest (25.–27.09.) erlebt ihr hier mit Laternen und Mondkuchen.",
    zones: [
      {
        id: "sh-bund",
        tag: "Tag-Idee · Klassiker",
        title: "Der Bund, Nanjing Road & Museum",
        summary: "Die berühmte Uferpromenade mit Kolonialbauten auf der einen und der Wolkenkratzer-Skyline auf der anderen Seite, dazu Chinas beste Sammlung alter Kunst.",
        walkFromHotel: "Metro Linie 1, ~15 Min.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Bund_2.jpg/1280px-The_Bund_2.jpg",
        transportNote: "Shanghais Metro ist die beste Chinas: klimatisiert, beschriftet auf Englisch und fast überall mit Aufzügen. Die Bund-Promenade ist eine erhöhte, komplett ebene Plattform – wunderbar zum Schieben, allerdings führen Treppen hinauf (Aufzüge gibt es an den Enden). Abends ab ca. 18:30 Uhr wird die Skyline beleuchtet.",
        route: { fromHotel: false, mode: "transit" },
        sights: [
          { name: "Der Bund", cn: "外滩", mapsName: "The Bund, Shanghai",
            desc: "1,5 km Uferpromenade mit 52 historischen Gebäuden im Rücken und der Pudong-Skyline gegenüber. Der ikonischste Blick Chinas – abends beleuchtet noch spektakulärer.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Bund_2.jpg/1280px-The_Bund_2.jpg",
            lat: 31.2397, lng: 121.4900, stroller: "yes",
            badges: ["Kostenlos", "Oben eben", "Abends beleuchtet"] },
          { name: "Nanjing Road", cn: "南京路", mapsName: "Nanjing Road Pedestrian Street, Shanghai",
            desc: "Chinas berühmteste Einkaufsstraße, auf über einem Kilometer autofrei. Verbindet den Volksplatz direkt mit dem Bund – bequem und eben zu schieben.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/East_Nanjing_Road_2020_%2850361842166%29.jpg/1280px-East_Nanjing_Road_2020_%2850361842166%29.jpg",
            lat: 31.2360, lng: 121.4790, stroller: "yes",
            badges: ["Autofrei", "Klimatisierte Malls"] },
          { name: "Volksplatz & Park", cn: "人民广场", mapsName: "People's Square, Shanghai",
            desc: "Grünes Zentrum der Stadt mit Park, Teichen und Museen ringsum. Guter Ort für eine Pause zwischen Shopping und Kultur.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/People_Square_seen_from_Urban_Planning_Exhibition_Center.JPG/1280px-People_Square_seen_from_Urban_Planning_Exhibition_Center.JPG",
            lat: 31.2300, lng: 121.4750, stroller: "yes",
            badges: ["Park", "Metro-Knotenpunkt"] },
          { name: "Shanghai Museum", cn: "上海博物馆", mapsName: "Shanghai Museum, People's Square",
            desc: "Herausragende Sammlung von Bronzen, Keramik und Kalligrafie – und das kostenlos. Klimatisiert, barrierefrei mit Aufzügen: ideal an einem heißen Nachmittag.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Shanghai_Museum_exterior_1.jpg/1280px-Shanghai_Museum_exterior_1.jpg",
            lat: 31.2286, lng: 121.4750, stroller: "yes",
            badges: ["Eintritt frei", "Klimatisiert", "Barrierefrei"],
            ticketUrl: "https://www.shanghaimuseum.net/" },
        ],
        restaurants: [
          { name: "Yang's Fried Dumplings (小杨生煎)", mapsName: "Yang's Fried Dumplings Shanghai",
            desc: "Shanghais berühmte Sheng Jian Bao: unten knusprig gebraten, innen mit heißer Brühe gefüllt. Günstig, schnell und ein echtes Stück Stadtkultur.",
            lat: 31.2340, lng: 121.4760, price: "3–8 € / Portion",
            badges: ["Lokale Spezialität", "Sehr günstig", "Enthält Weizen"] },
          { name: "Din Tai Fung", mapsName: "Din Tai Fung Shanghai",
            desc: "Verlässlich sauber, klimatisiert und mit Hochstühlen – Xiao Long Bao und gedämpfte Gerichte, die auch Kinder mögen. Die sichere Wahl mit Baby.",
            lat: 31.2310, lng: 121.4740, price: "18–30 € / Person",
            badges: ["Familienfreundlich", "Hochstühle", "Klimatisiert"] },
          { name: "Bowl- & Saft-Cafés am Bund", mapsName: "healthy cafe bowls The Bund Shanghai",
            desc: "Shanghai hat die westlichste Café-Szene Chinas: Salate, Bowls, Smoothies und Brunch, mit klar gekennzeichneten veganen und glutenfreien Optionen.",
            lat: 31.2380, lng: 121.4870, price: "10–22 € / Gericht",
            badges: ["Gesund", "Bowls", "Glutenfrei"] },
        ],
      },
      {
        id: "sh-pudong",
        tag: "Tag-Idee · Zukunft",
        title: "Pudong – Wolkenkratzer & Aquarium",
        summary: "Auf 546 Meter Höhe im zweithöchsten Gebäude der Welt, dazu der Fernsehturm Oriental Pearl und ein großes Aquarium – ein Tag ganz ohne Treppen.",
        walkFromHotel: "Metro Linie 2 unter dem Fluss, ~20 Min.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Pudong_Shanghai_November_2017_panorama.jpg/1280px-Pudong_Shanghai_November_2017_panorama.jpg",
        transportNote: "Mit der Metro Linie 2 bis Lujiazui – die Station liegt mitten zwischen den Wolkenkratzern. Rund um Lujiazui gibt es einen erhöhten Fußgänger-Rundweg mit Aufzügen, komplett autofrei und eben. Alles hier ist per Aufzug erreichbar: der babyfreundlichste Sightseeing-Tag der Reise.",
        route: { fromHotel: false, mode: "transit" },
        sights: [
          { name: "Shanghai Tower", cn: "上海中心大厦", mapsName: "Shanghai Tower Observation Deck",
            desc: "Mit 632 m das höchste Gebäude Chinas. Einer der schnellsten Aufzüge der Welt bringt euch in 55 Sekunden auf 546 m. Komplett barrierefrei, keine einzige Stufe.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Pudong_Shanghai_November_2017_panorama.jpg/1280px-Pudong_Shanghai_November_2017_panorama.jpg",
            lat: 31.2336, lng: 121.5055, stroller: "yes",
            badges: ["Barrierefrei", "Klarer Tag = beste Sicht", "Tickets vorab"] },
          { name: "Oriental Pearl Tower", cn: "东方明珠", mapsName: "Oriental Pearl Tower, Shanghai",
            desc: "Der Fernsehturm mit den rosa Kugeln ist Shanghais Wahrzeichen. Mit Glasboden-Aussichtsplattform und einem sehenswerten Stadtgeschichtsmuseum im Sockel.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Oriental_Pearl_Tower_20251126.jpg/1280px-Oriental_Pearl_Tower_20251126.jpg",
            lat: 31.2397, lng: 121.4998, stroller: "yes",
            badges: ["Glasboden", "Museum im Sockel", "Aufzüge"] },
          { name: "Shanghai Ocean Aquarium", cn: "上海海洋水族馆", mapsName: "Shanghai Ocean Aquarium",
            desc: "Großes Aquarium mit einem 155 m langen Unterwassertunnel – Haie und Rochen schwimmen über euch hinweg. Für Babys sind die leuchtenden Becken faszinierend.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Shanghai_Ocean_Aquarium.jpg/1280px-Shanghai_Ocean_Aquarium.jpg",
            lat: 31.2420, lng: 121.5000, stroller: "yes",
            badges: ["Top mit Baby", "Klimatisiert", "Kinderwagen ok"] },
        ],
        restaurants: [
          { name: "Foodcourts in Lujiazui (IFC / Super Brand Mall)", mapsName: "Shanghai IFC Mall food court Lujiazui",
            desc: "Die Malls unter den Wolkenkratzern haben große Foodcourts mit asiatischer und westlicher Küche, Wickelräumen und Stillzimmern – alles klimatisiert.",
            lat: 31.2380, lng: 121.5010, price: "10–25 € / Gericht",
            badges: ["Wickelraum", "Klimatisiert", "Große Auswahl"] },
          { name: "Restaurants mit Skyline-Blick", mapsName: "restaurant view The Bund Pudong Shanghai",
            desc: "Am Ufer von Pudong gibt es Restaurants mit Blick zurück auf den Bund – am schönsten zur blauen Stunde. Reservierung empfohlen.",
            lat: 31.2400, lng: 121.4960, price: "25–50 € / Person",
            badges: ["Aussicht", "Reservieren"] },
        ],
      },
      {
        id: "sh-altstadt",
        tag: "Tag-Idee · Gärten & Viertel",
        title: "Yu-Garten, Xintiandi & Franz. Viertel",
        summary: "Klassischer chinesischer Garten aus dem 16. Jahrhundert, die Kunstgassen von Tianzifang und die platanengesäumten Straßen des alten Französischen Viertels.",
        walkFromHotel: "Xintiandi fußläufig, Yu-Garten 2 Stationen",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Shanghai_-_Yu_Garden_-_0035.jpg/1280px-Shanghai_-_Yu_Garden_-_0035.jpg",
        transportNote: "Diese Zone beginnt direkt vor eurer Haustür: Xintiandi und der Fuxing-Park sind fußläufig, der Yu-Garten zwei Metro-Stationen entfernt. Achtung im Yu-Garten: viele Schwellen, Brücken und Stufen – hier ist die Trage besser. Das Französische Viertel dagegen ist flach und schattig, ideal zum Schieben.",
        route: { fromHotel: true, mode: "walking" },
        sights: [
          { name: "Yu-Garten", cn: "豫园", mapsName: "Yu Garden, Shanghai",
            desc: "Klassischer Ming-Garten von 1559 mit Pavillons, Teichen und Zickzack-Brücken. Wunderschön, aber voller Schwellen, enger Durchgänge und Stufen.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Shanghai_-_Yu_Garden_-_0035.jpg/1280px-Shanghai_-_Yu_Garden_-_0035.jpg",
            lat: 31.2270, lng: 121.4920, stroller: "no",
            badges: ["Trage empfohlen", "Viele Schwellen", "Basar drumherum voll"],
            ticketUrl: "https://www.yugarden.com.cn/" },
          { name: "Xintiandi", cn: "新天地", mapsName: "Xintiandi, Shanghai",
            desc: "Restaurierte Shikumen-Steinhäuser, heute Cafés, Restaurants und Boutiquen in autofreien Gassen. Gepflegt, eben und sehr angenehm mit Kinderwagen – gleich beim Hotel.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Xintiandi5.jpg/1280px-Xintiandi5.jpg",
            lat: 31.2210, lng: 121.4750, stroller: "yes",
            badges: ["Autofrei", "Direkt am Hotel", "Viele Cafés"] },
          { name: "Tianzifang", cn: "田子坊", mapsName: "Tianzifang, Shanghai",
            desc: "Labyrinth aus engen Gassen mit Künstlerateliers, Werkstätten und Teeläden. Charmant, aber sehr eng – mit Kinderwagen schwierig, mit Trage perfekt.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Shanghai_Tianzifang_%E4%B8%8A%E6%B5%B7%E7%94%B0%E5%AD%90%E5%9D%8A_-_panoramio.jpg/1280px-Shanghai_Tianzifang_%E4%B8%8A%E6%B5%B7%E7%94%B0%E5%AD%90%E5%9D%8A_-_panoramio.jpg",
            lat: 31.2100, lng: 121.4680, stroller: "no",
            badges: ["Sehr eng", "Trage besser", "Kunsthandwerk"] },
          { name: "Fuxing-Park & Französisches Viertel", cn: "复兴公园", mapsName: "Fuxing Park, Shanghai",
            desc: "Park im französischen Stil, morgens voller Tai-Chi-Gruppen und Tänzer. Die umliegenden Straßen mit ihren Platanen sind die schönsten Spazierwege Shanghais.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Fuxing_Park%2C_Shanghai.JPG/1280px-Fuxing_Park%2C_Shanghai.JPG",
            lat: 31.2200, lng: 121.4680, stroller: "yes",
            badges: ["Eintritt frei", "Schattige Alleen", "Morgens Tai Chi"] },
        ],
        restaurants: [
          { name: "Jesse / Shanghainese Küche", mapsName: "Shanghainese restaurant former French Concession",
            desc: "Im Französischen Viertel gibt es klassische Shanghai-Küche: geschmortes Schweinefleisch, Flusskrebse und süßlich-sojaige Saucen. Reservierung sinnvoll.",
            lat: 31.2150, lng: 121.4600, price: "18–35 € / Person",
            badges: ["Lokal", "Reservieren", "Sojasauce enthält Weizen"] },
          { name: "Cafés & Bäckereien in Xintiandi", mapsName: "cafe Xintiandi Shanghai",
            desc: "Direkt beim Hotel: Cafés mit Frühstück, Brunch, Obst und gutem Kaffee. Mit Baby der bequemste Start in den Tag, ohne Metro-Fahrt.",
            lat: 31.2212, lng: 121.4752, price: "8–20 € / Person",
            badges: ["Fußläufig", "Brunch", "Gesund"] },
          { name: "Vegetarisch & glutenfrei im Franz. Viertel", mapsName: "vegan gluten free restaurant former French Concession Shanghai",
            desc: "Das Viertel hat die größte Dichte an veganen und glutenfreien Restaurants in ganz China – mit englischen Karten und klarer Kennzeichnung.",
            lat: 31.2170, lng: 121.4620, price: "12–28 € / Gericht",
            badges: ["Vegan", "Glutenfrei", "Englische Karte"] },
        ],
      },
      {
        id: "sh-ausfluege",
        tag: "Tag-Idee · Ausflüge",
        title: "Wasserstadt Zhujiajiao & Hangzhou",
        summary: "Kanäle, Steinbrücken und Boote in der 1.700 Jahre alten Wasserstadt – oder mit dem Schnellzug in 45 Minuten zum berühmten Westsee von Hangzhou.",
        walkFromHotel: "Metro Linie 17 bzw. Schnellzug ab Hongqiao",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/1_zhujiajiao_2023_aerial.jpg/1280px-1_zhujiajiao_2023_aerial.jpg",
        transportNote: "Zhujiajiao erreicht ihr bequem mit der Metro Linie 17 (ca. 1 Std., keine Umstiege nötig ab Linie 1 → 2 → 17). Hangzhou ist mit dem Schnellzug ab Hongqiao in nur 45–60 Min. erreichbar – ein perfekter Tagesausflug, der zu eurem „möglichst alles mit dem Zug“-Plan passt. Beides sind Alternativen: sucht euch je nach Babylaune eines aus.",
        route: { fromHotel: false, mode: "transit" },
        sights: [
          { name: "Wasserstadt Zhujiajiao", cn: "朱家角", mapsName: "Zhujiajiao Ancient Town, Shanghai",
            desc: "Kanäle, 36 alte Steinbrücken und Häuser aus der Ming-Zeit – „Venedig Shanghais“, aber nur eine Metrofahrt entfernt. Gassen sind gepflastert und teils eng.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/1_zhujiajiao_2023_aerial.jpg/1280px-1_zhujiajiao_2023_aerial.jpg",
            lat: 31.1110, lng: 121.0530, stroller: "careful",
            badges: ["Metro Linie 17", "Kopfsteinpflaster", "Bootsfahrten"] },
          { name: "Westsee Hangzhou", cn: "西湖", mapsName: "West Lake, Hangzhou",
            desc: "UNESCO-Welterbe und einer der schönsten Seen Chinas, mit Pagoden, Weiden und Dämmen. Die Uferwege sind eben und breit – ein herrlicher Kinderwagen-Tag.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/West_Lake%2C_Hangzhou_2025.jpg/1280px-West_Lake%2C_Hangzhou_2025.jpg",
            lat: 30.2450, lng: 120.1490, stroller: "yes",
            badges: ["45 Min. Schnellzug", "Uferweg eben", "Eintritt frei"],
            inRoute: false },
          { name: "Jing'an-Tempel", cn: "静安寺", mapsName: "Jing'an Temple, Shanghai",
            desc: "Goldglänzender Tempel zwischen Hochhäusern und Einkaufsstraßen – der Kontrast macht ihn besonders. Gute Alternative, wenn ein ganzer Ausflugstag zu viel ist.",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/%E9%9D%99%E5%AE%89%E5%AF%BA%C2%B7%E4%B8%8A%E6%B5%B7%E9%9D%99%E5%AE%89.jpg/1280px-%E9%9D%99%E5%AE%89%E5%AF%BA%C2%B7%E4%B8%8A%E6%B5%B7%E9%9D%99%E5%AE%89.jpg",
            lat: 31.2240, lng: 121.4450, stroller: "careful",
            badges: ["Direkt an der Metro", "Einzelne Stufen", "Halber Tag"],
            inRoute: false },
        ],
        restaurants: [
          { name: "Kanalrestaurants in Zhujiajiao", mapsName: "restaurant Zhujiajiao water town",
            desc: "Kleine Lokale direkt am Wasser servieren Flussfisch, Reis und in Bambusblättern gedämpfte Reispäckchen (Zongzi) – letztere sind meist glutenfrei.",
            lat: 31.1115, lng: 121.0535, price: "8–20 € / Gericht",
            badges: ["Am Wasser", "Zongzi glutenfrei"] },
          { name: "Teehäuser am Westsee", mapsName: "tea house West Lake Hangzhou",
            desc: "Hangzhou ist berühmt für seinen Longjing-Grüntee. In den Teehäusern am See gibt es dazu leichte vegetarische Gerichte – sehr entspannt mit Baby.",
            lat: 30.2460, lng: 120.1480, price: "10–25 € / Person",
            badges: ["Grüntee", "Vegetarisch", "Ruhig"] },
        ],
      },
    ],
  },
];
